Profiles
DevN00bs/FastHomeNextAPI pull request #15
Opened 2022-02-26 12:09 UTC by Pwma77

Let's suppose get and put work, heh.
Get obtains the data when current user is equals to actual profile "owner/user". But, I left a draft in case it needs to be compared to a property. One more thing is that I don't remember if I put just to show one or more data, so this "get" requires a bit more attention xD.
Put works perfectly, I hope so... Still, both need like a bit more "security" but so far that's it buddy. Hope we can merge them cuz are already working at this point, otherwise lemme know some changes and I'll make them maybe on Sunday or idk

2022-02-26 12:21 UTC, Pwma77 commented
Se bugeo por el linter, pero mañana veo qué arreglo

2022-02-27 06:18 UTC, BrandomRobor requested changes

2022-02-27 06:18 UTC, BrandomRobor commented on src/models/profiles.py
> +    email = m.EmailField(unique=True)
```suggestion
```
Este campo ya no debería de existir

2022-02-27 06:18 UTC, BrandomRobor commented on src/models/profiles.py
> +    twit_link = String()
Estos esquemas son exactamente iguales, hay alguna razón para mantener ambos?

2022-02-27 06:18 UTC, BrandomRobor commented on .github/mapi.sarif
> +{}
Uh, un remanente de mis pruebas, necesito borrar eso

2022-02-27 06:18 UTC, BrandomRobor commented on src/controllers/profiles.py
> +    return ControllerStatus.SUCCESS
Falta una nueva línea aquí, es probable que por eso falló el linter

2022-02-27 06:18 UTC, BrandomRobor commented on src/controllers/profiles.py
> +    user_id = auth.current_user
Nope, así no funciona esto
```suggestion
```

2022-02-27 06:18 UTC, BrandomRobor commented on src/controllers/profiles.py
> +        # prop_owner = prop.PropertyDoc.objects.get(id=data["id"])
Es necesario mantener código viejo?

2022-02-27 06:18 UTC, BrandomRobor commented on src/controllers/profiles.py
> +    if str(user_id["id"]) == str(prof_id["user"].id):
Convertir un string a un string es un poco redundante
```suggestion
    if user_id["id"] == str(prof_id["user"].id):
```

2022-02-27 06:18 UTC, BrandomRobor commented on src/controllers/profiles.py
> +        prof_id = prof.ProfileDoc.objects.get()
Aquí falta filtrar por ID, de momento este código te devuleve el primer documento de la lista

2022-02-27 06:18 UTC, BrandomRobor commented on src/controllers/profiles.py
> +    if str(user_id == auth.current_user):
Nope, el decoder "auth" NO se debe de usar en el controlador

2022-02-27 06:18 UTC, BrandomRobor commented on src/controllers/profiles.py
> +            if data["phone"] == "string":
Uh, esta condición es realmente necesaria?

2022-02-27 06:18 UTC, BrandomRobor commented on src/controllers/profiles.py
> +            return ControllerStatus.ERROR
Un try dento de otro try? Porqué?

2022-02-27 06:18 UTC, BrandomRobor commented on src/routes/profiles.py
> +    return current
En el controlador revisas errores y retornas códigos de error, pero si no los revisas en la ruta todos los errores regresarán 200 y eso es malo

2022-02-27 06:18 UTC, BrandomRobor commented on src/routes/profiles.py
> +@output(m.ProfileData(many=True), 200)
No, en esta ruta sólo queremos que regrese un solo resultado
```suggestion
@output(m.ProfileData, 200)
```

2022-02-27 06:18 UTC, BrandomRobor commented on src/server.py
> +app.register_blueprint(prof)
Falta línea al final del archivo

2022-02-27 06:21 UTC, BrandomRobor commented on src/controllers/profiles.py
> +            return ControllerStatus.ERROR
Y acabo de ver que atrapan la misma excepción en todos, completamente innecesario

2022-02-27 19:34 UTC, Pwma77 commented on .github/mapi.sarif
> +{}
Bien bien

2022-02-27 19:36 UTC, Pwma77 commented on src/models/profiles.py
> +    email = m.EmailField(unique=True)
roger

2022-02-27 19:36 UTC, Pwma77 commented on src/models/profiles.py
> +    twit_link = String()
No realmente, los usé para probar un par de cosas y olvidé borrar el extra lol

2022-02-27 19:40 UTC, Pwma77 commented on src/server.py
> +app.register_blueprint(prof)
Uhh se me hace que la puse después de hacer el push, orita pusheo again

2022-02-27 19:42 UTC, Pwma77 commented on src/controllers/profiles.py
> +    user_id = auth.current_user
Va, lo borro XD

2022-02-27 19:43 UTC, Pwma77 commented on src/controllers/profiles.py
> +    user_id = auth.current_user
Recuerdo que lo puse en la ruta so creo que no lo necesito por acá (ahora que lo veo)

2022-02-27 19:44 UTC, Pwma77 commented on src/controllers/profiles.py
> +        # prop_owner = prop.PropertyDoc.objects.get(id=data["id"])
Nope, creo que lo dejé porque funcionó y no quise moverle xD
Maybe diré esto en un par de comments, qué bueno que me los recuerdas. Thanks

2022-02-27 19:47 UTC, Pwma77 commented on src/controllers/profiles.py
> +        prof_id = prof.ProfileDoc.objects.get()
Filtrar por ID me mandaba error con mongo porque no coincidían los datos, alguna recomendación?

2022-02-27 19:48 UTC, Pwma77 commented on src/controllers/profiles.py
> +        prof_id = prof.ProfileDoc.objects.get()
De momento dejé esa parte así por si se necesitaba probar, still necesita ese fix

2022-02-27 19:49 UTC, Pwma77 commented on src/controllers/profiles.py
> +    if str(user_id["id"]) == str(prof_id["user"].id):
Pensaba que estaba como definiendolo, así como me habías dicho lol

2022-02-27 19:50 UTC, Pwma77 commented on src/controllers/profiles.py
> +    if str(user_id == auth.current_user):
Oh no. Entonces sería más como pasarlo en la ruta, me lo traigo como parámetro y lo uso como el "user_id" no?

2022-02-27 19:51 UTC, Pwma77 commented on src/controllers/profiles.py
> +    if str(user_id == auth.current_user):
Igual sigo haciendo los cambios como me los has ido comentando

2022-02-27 19:51 UTC, Pwma77 commented on src/controllers/profiles.py
> +    if str(user_id == auth.current_user):
> Oh no. Entonces sería más como pasarlo en la ruta, me lo traigo como parámetro y lo uso como el "user_id" no?

Wait no, ya vi

2022-02-27 19:52 UTC, Pwma77 commented on src/controllers/profiles.py
> +    if str(user_id == auth.current_user):
Entonces, estoy igualando el mismo id al mismo id so es una condición useless?

2022-02-27 19:55 UTC, Pwma77 commented on src/controllers/profiles.py
> +            if data["phone"] == "string":
De momento, sí. Quería usar todos los campos, pero no encontré una forma. Está curioso porque el dato por defecto es literalmente "string", so para verificar que fuese a crear un nuevo campo no encontré otra manera. Además pensaba que si del front ponen por defecto que no tenga nada y lo guardan, está de igual forma actualizando el dato, por lo que "creo" no debería haber problema. No sé si se te pueda ocurrir alguna alternativa (directamente en el modelo poner dato inicial estaría bien, pero no encontré cómo)

2022-02-27 19:56 UTC, Pwma77 commented on src/controllers/profiles.py
> +            return ControllerStatus.ERROR
Ya sabes, haciendo una mezcladera hasta que funcione; como no daba errores ya no lo toqué x
Voy a cambiarlo

2022-02-27 19:59 UTC, Pwma77 commented on src/controllers/profiles.py
> +            return ControllerStatus.ERROR
Ah ya me acordé, te iba a preguntar por posibles escenarios para ponerlos (por motivos de seguridad), pero los terminé dejando con el mismo error. Creo que debo corregir el hecho de dejar mugrero que no uso lol

2022-02-27 19:59 UTC, Pwma77 commented on src/controllers/profiles.py
> +    return ControllerStatus.SUCCESS
Creo que sí la puse, pero hice push antes de ponerla lol

2022-02-27 20:00 UTC, Pwma77 commented on src/routes/profiles.py
> +@output(m.ProfileData(many=True), 200)
Ah sí, again para pruebas. My bad

2022-02-27 20:03 UTC, Pwma77 commented on src/routes/profiles.py
> +    return current
Hmm, creo que aquí necesito ayuda, oops

2022-02-27 20:07 UTC, BrandomRobor commented on src/controllers/profiles.py
> +    if str(user_id["id"]) == str(prof_id["user"].id):
No, definir los tipos se hace en los parámetros

2022-02-27 21:07 UTC, Pwma77 reviewed
En general, el nuevo commit es para verificar si lo que me comentaste acerca de remover o cambiar, va por buen camino. No añadí nada nuevo, sólo removí; no testée, still es para que me des visto bueno/malo plz y de ahí continuar

2022-02-27 21:08 UTC, Pwma77 commented
> En general, el nuevo commit es para verificar si lo que me comentaste acerca de remover o cambiar, va por buen camino. No añadí nada nuevo, sólo removí; no testée, still es para que me des visto bueno/malo plz y de ahí continuar

Ah, los comentarios con los que respondí lo demás de ver si como me puedes explicar ciertas cositas, se mantienen plz

2022-02-27 22:46 UTC, BrandomRobor requested changes
Mejor, pero aún no. Lo veremos en la noche

2022-03-02 00:27 UTC, BrandomRobor approved these changes
Looks güd to me

2022-03-02 01:36 UTC, merged