Tests
DevN00bs/FastHomeNextAPI pull request #18
Opened 2022-03-06 22:18 UTC by Pwma77

It's supposed to be already working, still it needs for you to check plz xD
Tengo que mejorar la estructura porque creo que se mira un poco "cochino", pero me enfoqué en que pasaran los tests. De momento con que me mandes feedback, lo corrijo más tarde. Creo que ni siquiera tuve que tocar el controlador, todo se veia bien y pues espero haberlo hecho bien en cuestión de verificar los tests (fue de lo más complicadito para mi orita, pero más que nada en pensarle sobre qué comparar porque no podía ver tal cual la bd lol)
Espero no salir con más dudas jej, pero te quería preguntar cómo funcionan exactamente las lambda y los diccionarios (diccionarios enfocados en el assertDict).
Lo dejo en draft para que lo cheques, pero luego viendo ya cómo queda, pongo el otro.

2022-03-07 23:09 UTC, BrandomRobor requested changes

2022-03-07 23:09 UTC, BrandomRobor commented on src/controllers/properties.py
> +    if str(usr.User.objects.get().id) != user_id:
Usar el get sin parámetro no es correcto, no queda claro que quisiste intentar aquí

2022-03-07 23:09 UTC, BrandomRobor commented on test/properties.py
> +        self.assertEqual(result[1].get(), obj)
No, la idea es revisar que los datos de una propiedad sea igual a los datos que ingresaste
```suggestion
        self.assertEqual(result[1].first().address, self._register_prop["address"])
```

2022-03-07 23:09 UTC, BrandomRobor commented on test/properties.py
> +        self.assertEqual(PropertyDoc.objects.get(owner=self._userId).price, _price)
Preferiría que filtraras por el id de la propiedad, ya que esto daría error si hubiera varias propiedades con el mismo dueño, pero está bien
```suggestion
        self.assertEqual(PropertyDoc.objects.get(id=self._propId).price, _price)
```

2022-03-07 23:09 UTC, BrandomRobor commented on test/properties.py
> +        self.assertNotEqual(test_id, self._userId)
Agarra la propiedad justo como hiciste con la línea de abajo y revisa que el id de prueba no coincida con el id del dueño

2022-03-07 23:09 UTC, BrandomRobor commented on test/properties.py
> +        self.assertNotEqual(PropertyDoc.objects.get(id=self._propId).price, _price)
Aquí necesitas revisar que no se editó el precio, así que compara con el precio original, no con el nuevo

2022-03-08 03:22 UTC, Pwma77 commented on src/controllers/properties.py
> +    if str(usr.User.objects.get().id) != user_id:
La verdad, no tengo idea qué intenté; como que pensaba que con lo que me habias dicho de "verificar que la propiedad exista" te referías a que como hiciera una condición que dijera si existe, peeeeeeero en el test según yo ya lo checa. La voy a borrar porque no la veo necesaria siendo que nunca la tocaría, qué opinas?

2022-03-08 03:27 UTC, Pwma77 commented on test/properties.py
> +        self.assertEqual(result[1].get(), obj)
Entonces con el ".first().address" estaríamos tomando el primer address en la bd?

2022-03-08 03:32 UTC, Pwma77 commented on test/properties.py
> +        self.assertEqual(PropertyDoc.objects.get(owner=self._userId).price, _price)
Nice. Creo que había puesto el owner para probar si funcionaba y como jaló no le moví xD. Grax por el comment

2022-03-08 05:43 UTC, BrandomRobor commented on src/controllers/properties.py
> +    if str(usr.User.objects.get().id) != user_id:
> no la veo necesaria siendo que nunca la tocaría

Has respondido tu propia respuesta

2022-03-08 05:43 UTC, BrandomRobor commented on test/properties.py
> +        self.assertEqual(result[1].get(), obj)
La primera propiedad de la lista y luego su dirección, pero si

2022-03-08 06:16 UTC, Pwma77 commented on test/properties.py
> +        self.assertNotEqual(test_id, self._userId)
Me distraje con unas cosillas, pero I'm back. Sip, orita le hago commit y ya me dices si es como lo hice plz.

2022-03-08 06:53 UTC, Pwma77 commented on test/properties.py
> +        self.assertNotEqual(PropertyDoc.objects.get(id=self._propId).price, _price)
Ya lo pude sacar, pero no creo que sea la forma correcta (no da error, pero no me gusta). Orita que le haga commit se va a ver.  Del dato que me traigo de la bd haz de cuenta que me lo pone como "Decimal("1200.00")" (algo así; el punto son los ".00") y pues estrictamente los trae así. Ya intenté poner el Decimal() de la librería de decimal y lo transforma, pero sólo con un ".0" en valor, so como son diferentes vale queso XD.
Puse ".11" al final del valor inicial, al parecer ya no da error, pero es probarlo de esta forma soooooooooo no sé si tengas otra idea o algo así para que me digas cuando lo veas jiji

2022-03-09 00:11 UTC, BrandomRobor requested changes

2022-03-09 00:11 UTC, BrandomRobor commented on test/properties.py
> +        self.assertNotEqual(PropertyDoc.objects.get(id=self._propId).id, self._propId)
Aquí hay que revisar que el usuario que estás pasando (en este caso test_id) no es el mismo que el de la propiedad que tratas de borrar. En este momento estás revisando si el id de la propiedad no es igual que el id de la propiedad, lo cual siempre será falso ya que la base de datos te devuelve un ObjectID y no un string

2022-03-09 00:26 UTC, Pwma77 commented on test/properties.py
> +        self.assertNotEqual(PropertyDoc.objects.get(id=self._propId).id, self._propId)
Voy a subirlo en un momento; quedaría entonces como el test_id diferente al owner del id que encuentre de la propiedad, no?

2022-03-10 00:44 UTC, BrandomRobor requested changes

2022-03-10 00:44 UTC, BrandomRobor commented on test/properties.py
> +        self.assertNotEqual(PropertyDoc.objects.get(id=self._propId).owner, test_id)
Falta referenciar el id aquí, comparar un documento con un string siempre dará false

2022-03-10 00:44 UTC, BrandomRobor commented on test/properties.py
> +        self.assertEqual(result[1].address, obj_address)
Necesitas verificar con la dirección original, no con otra consulta a la base de datos
```suggestion
        self.assertEqual(result[1].address, self._register_prop["address"])
```
No olvídes borrar la variable obj_address después

2022-03-10 01:42 UTC, Pwma77 commented on test/properties.py
> +        self.assertNotEqual(PropertyDoc.objects.get(id=self._propId).owner, test_id)
Entonces sólo sería necesario hacerlo string como en el fix de la #230?

2022-03-10 01:45 UTC, BrandomRobor commented on test/properties.py
> +        self.assertNotEqual(PropertyDoc.objects.get(id=self._propId).owner, test_id)
Correcto

2022-03-10 03:25 UTC, BrandomRobor requested changes

2022-03-10 03:25 UTC, BrandomRobor commented on test/properties.py
> +        self.assertNotEqual(str(PropertyDoc.objects.get(id=self._propId).owner), test_id)
Nope, aún no
```suggestion
        self.assertNotEqual(str(PropertyDoc.objects.get(id=self._propId).owner.id), test_id)
```

2022-03-10 04:01 UTC, BrandomRobor approved these changes

2022-03-10 04:02 UTC, merged